errors = {
    "General errors": {
        "0": {"error_num": 0, "title": "NO_ERROR", "description": "No error has occurred."},
        "1": {"error_num": 1, "title": "FAILED", "description": "Will be raised when a general error occurred."},
        "2": {"error_num": 2, "title": "SYS_ERROR", "description": "Will be raised when operating system error occurred."},
        "3": {"error_num": 3, "title": "OUT_OF_MEMORY", "description": "Will be raised when there is a memory shortage."},
        "4": {"error_num": 4, "title": "INTERNAL", "description": "Will be raised when an internal error occurred."},
        "5": {"error_num": 5, "title": "ILLEGAL_NUMBER", "description": "Will be raised when an illegal representation of a number was given."},
        "6": {"error_num": 6, "title": "NUMERIC_OVERFLOW", "description": "Will be raised when a numeric overflow occurred."},
        "7": {"error_num": 7, "title": "ILLEGAL_OPTION", "description": "Will be raised when an unknown option was supplied by the user."},
        "8": {"error_num": 8, "title": "DEAD_PID", "description": "Will be raised when a PID without a living process was found."},
        "9": {"error_num": 9, "title": "NOT_IMPLEMENTED", "description": "Will be raised when hitting an unimplemented feature."},
        "10": {"error_num": 10, "title": "BAD_PARAMETER", "description": "Will be raised when the parameter does not fulfill the requirements."},
        "11": {"error_num": 11, "title": "FORBIDDEN", "description": "Will be raised when you are missing permission for the operation."},
        "12": {"error_num": 12, "title": "OUT_OF_MEMORY_MMAP", "description": "Will be raised when there is a memory shortage."},
        "13": {"error_num": 13, "title": "CORRUPTED_CSV", "description": "Will be raised when encountering a corrupt csv line."},
        "14": {"error_num": 14, "title": "FILE_NOT_FOUND", "description": "Will be raised when a file is not found."},
        "15": {"error_num": 15, "title": "CANNOT_WRITE_FILE", "description": "Will be raised when a file cannot be written."},
        "16": {"error_num": 16, "title": "CANNOT_OVERWRITE_FILE", "description": "Will be raised when an attempt is made to overwrite an existing file."},
        "17": {"error_num": 17, "title": "TYPE_ERROR", "description": "Will be raised when a type error is encountered."},
        "18": {"error_num": 18, "title": "LOCK_TIMEOUT", "description": "Will be raised when there\u2019s a timeout waiting for a lock."},
        "19": {"error_num": 19, "title": "CANNOT_CREATE_DIRECTORY", "description": "Will be raised when an attempt to create a directory fails."},
        "20": {"error_num": 20, "title": "CANNOT_CREATE_TEMP_FILE", "description": "Will be raised when an attempt to create a temporary file fails."},
        "21": {"error_num": 21, "title": "REQUEST_CANCELED", "description": "Will be raised when a request is canceled by the user."},
        "22": {"error_num": 22, "title": "DEBUG", "description": "Will be raised intentionally during debugging."},
        "25": {"error_num": 25, "title": "IP_ADDRESS_INVALID", "description": "Will be raised when the structure of an IP address is invalid."},
        "27": {"error_num": 27, "title": "FILE_EXISTS", "description": "Will be raised when a file already exists."},
        "28": {"error_num": 28, "title": "LOCKED", "description": "Will be raised when a resource or an operation is locked."},
        "29": {"error_num": 29, "title": "DEADLOCK", "description": "Will be raised when a deadlock is detected when accessing collections."},
        "30": {
            "error_num": 30,
            "title": "SHUTTING_DOWN",
            "description": "Will be raised when a call cannot succeed because a server shutdown is already in progress.",
        },
        "31": {
            "error_num": 31,
            "title": "ONLY_ENTERPRISE",
            "description": "Will be raised when an Enterprise Edition feature is requested from the Community Edition.",
        },
        "32": {
            "error_num": 32,
            "title": "RESOURCE_LIMIT",
            "description": "Will be raised when the resources used by an operation exceed the configured maximum value.",
        },
        "33": {"error_num": 33, "title": "ARANGO_ICU_ERROR", "description": "will be raised if icu operations failed"},
        "34": {"error_num": 34, "title": "CANNOT_READ_FILE", "description": "Will be raised when a file cannot be read."},
        "35": {"error_num": 35, "title": "INCOMPATIBLE_VERSION", "description": "Will be raised when a server is running an incompatible version of ArangoDB."},
        "36": {"error_num": 36, "title": "DISABLED", "description": "Will be raised when a requested resource is not enabled."},
        "37": {"error_num": 37, "title": "MALFORMED_JSON", "description": "Will be raised when a JSON string could not be parsed."},
        "38": {
            "error_num": 38,
            "title": "STARTING_UP",
            "description": "Will be raised when a call cannot succeed because the server startup phase is still in progress.",
        },
    },
    "HTTP error status codes": {
        "400": {"error_num": 400, "title": "HTTP_BAD_PARAMETER", "description": "Will be raised when the HTTP request does not fulfill the requirements."},
        "401": {"error_num": 401, "title": "HTTP_UNAUTHORIZED", "description": "Will be raised when authorization is required but the user is not authorized."},
        "403": {"error_num": 403, "title": "HTTP_FORBIDDEN", "description": "Will be raised when the operation is forbidden."},
        "404": {"error_num": 404, "title": "HTTP_NOT_FOUND", "description": "Will be raised when an URI is unknown."},
        "405": {
            "error_num": 405,
            "title": "HTTP_METHOD_NOT_ALLOWED",
            "description": "Will be raised when an unsupported HTTP method is used for an operation.",
        },
        "406": {
            "error_num": 406,
            "title": "HTTP_NOT_ACCEPTABLE",
            "description": "Will be raised when an unsupported HTTP content type is used for an operation",
        },
        "408": {"error_num": 408, "title": "HTTP_REQUEST_TIMEOUT", "description": "Will be raised when a timeout occured."},
        "409": {"error_num": 409, "title": "HTTP_CONFLICT", "description": "Will be raised when a conflict occurs in an HTTP operation."},
        "410": {"error_num": 410, "title": "HTTP_GONE", "description": "Will be raised when the requested content has been permanently deleted."},
        "412": {"error_num": 412, "title": "HTTP_PRECONDITION_FAILED", "description": "Will be raised when a precondition for an HTTP request is not met."},
        "500": {"error_num": 500, "title": "HTTP_SERVER_ERROR", "description": "Will be raised when an internal server is encountered."},
        "501": {"error_num": 501, "title": "HTTP_NOT_IMPLEMENTED", "description": "Will be raised when an API is called this is not implemented in general"},
        "503": {"error_num": 503, "title": "HTTP_SERVICE_UNAVAILABLE", "description": "Will be raised when a service is temporarily unavailable."},
        "504": {
            "error_num": 504,
            "title": "HTTP_GATEWAY_TIMEOUT",
            "description": "Will be raised when a service contacted by ArangoDB does not respond in a timely manner.",
        },
    },
    "HTTP processing errors": {
        "600": {"error_num": 600, "title": "HTTP_CORRUPTED_JSON", "description": "Will be raised when a string representation of a JSON object is corrupt."},
        "601": {"error_num": 601, "title": "HTTP_SUPERFLUOUS_SUFFICES", "description": "Will be raised when the URL contains superfluous suffices."},
    },
    "Internal ArangoDB storage errors": {
        "1000": {
            "error_num": 1000,
            "title": "ARANGO_ILLEGAL_STATE",
            "description": "Internal error that will be raised when the datafile is not in the required state.",
        },
        "1004": {
            "error_num": 1004,
            "title": "ARANGO_READ_ONLY",
            "description": "Internal error that will be raised when trying to write to a read-only datafile or collection.",
        },
        "1005": {
            "error_num": 1005,
            "title": "ARANGO_DUPLICATE_IDENTIFIER",
            "description": "Internal error that will be raised when a identifier duplicate is detected.",
        },
    },
    "External ArangoDB storage errors": {
        "1100": {"error_num": 1100, "title": "ARANGO_CORRUPTED_DATAFILE", "description": "Will be raised when a corruption is detected in a datafile."},
        "1101": {
            "error_num": 1101,
            "title": "ARANGO_ILLEGAL_PARAMETER_FILE",
            "description": "Will be raised if a parameter file is corrupted or cannot be read.",
        },
        "1102": {
            "error_num": 1102,
            "title": "ARANGO_CORRUPTED_COLLECTION",
            "description": "Will be raised when a collection contains one or more corrupted data files.",
        },
        "1104": {"error_num": 1104, "title": "ARANGO_FILESYSTEM_FULL", "description": "Will be raised when the filesystem is full."},
        "1107": {
            "error_num": 1107,
            "title": "ARANGO_DATADIR_LOCKED",
            "description": "Will be raised when the database directory is locked by a different process.",
        },
    },
    "General ArangoDB storage errors": {
        "1200": {
            "error_num": 1200,
            "title": "ARANGO_CONFLICT",
            "description": "Will be raised when updating or deleting a document and a conflict has been detected.",
        },
        "1202": {"error_num": 1202, "title": "ARANGO_DOCUMENT_NOT_FOUND", "description": "Will be raised when a document with a given identifier is unknown."},
        "1203": {
            "error_num": 1203,
            "title": "ARANGO_DATA_SOURCE_NOT_FOUND",
            "description": "Will be raised when a collection or View with the given identifier or name is unknown.",
        },
        "1204": {"error_num": 1204, "title": "ARANGO_COLLECTION_PARAMETER_MISSING", "description": "Will be raised when the collection parameter is missing."},
        "1205": {"error_num": 1205, "title": "ARANGO_DOCUMENT_HANDLE_BAD", "description": "Will be raised when a document identifier is corrupt."},
        "1207": {"error_num": 1207, "title": "ARANGO_DUPLICATE_NAME", "description": "Will be raised when a name duplicate is detected."},
        "1208": {"error_num": 1208, "title": "ARANGO_ILLEGAL_NAME", "description": "Will be raised when an illegal name is detected."},
        "1209": {"error_num": 1209, "title": "ARANGO_NO_INDEX", "description": "Will be raised when no suitable index for the query is known."},
        "1210": {"error_num": 1210, "title": "ARANGO_UNIQUE_CONSTRAINT_VIOLATED", "description": "Will be raised when there is a unique constraint violation."},
        "1212": {"error_num": 1212, "title": "ARANGO_INDEX_NOT_FOUND", "description": "Will be raised when an index with a given identifier is unknown."},
        "1213": {"error_num": 1213, "title": "ARANGO_CROSS_COLLECTION_REQUEST", "description": "Will be raised when a cross-collection is requested."},
        "1214": {"error_num": 1214, "title": "ARANGO_INDEX_HANDLE_BAD", "description": "Will be raised when a index identifier is corrupt."},
        "1216": {
            "error_num": 1216,
            "title": "ARANGO_DOCUMENT_TOO_LARGE",
            "description": "Will be raised when the document cannot fit into any datafile because of it is too large.",
        },
        "1217": {"error_num": 1217, "title": "ARANGO_COLLECTION_NOT_UNLOADED", "description": "Will be raised when a collection should be unloaded"},
        "1218": {
            "error_num": 1218,
            "title": "ARANGO_COLLECTION_TYPE_INVALID",
            "description": "Will be raised when an invalid collection type is used in a request.",
        },
        "1220": {
            "error_num": 1220,
            "title": "ARANGO_ATTRIBUTE_PARSER_FAILED",
            "description": "Will be raised when parsing an attribute name definition failed.",
        },
        "1221": {"error_num": 1221, "title": "ARANGO_DOCUMENT_KEY_BAD", "description": "Will be raised when a document key is corrupt."},
        "1222": {
            "error_num": 1222,
            "title": "ARANGO_DOCUMENT_KEY_UNEXPECTED",
            "description": "Will be raised when a user-defined document key is supplied for collections with auto key generation.",
        },
        "1224": {
            "error_num": 1224,
            "title": "ARANGO_DATADIR_NOT_WRITABLE",
            "description": "Will be raised when the server\u2019s database directory is not writable for the current user.",
        },
        "1225": {"error_num": 1225, "title": "ARANGO_OUT_OF_KEYS", "description": "Will be raised when a key generator runs out of keys."},
        "1226": {"error_num": 1226, "title": "ARANGO_DOCUMENT_KEY_MISSING", "description": "Will be raised when a document key is missing."},
        "1227": {
            "error_num": 1227,
            "title": "ARANGO_DOCUMENT_TYPE_INVALID",
            "description": "Will be raised when there is an attempt to create a document with an invalid type.",
        },
        "1228": {"error_num": 1228, "title": "ARANGO_DATABASE_NOT_FOUND", "description": "Will be raised when a non-existing database is accessed."},
        "1229": {"error_num": 1229, "title": "ARANGO_DATABASE_NAME_INVALID", "description": "Will be raised when an invalid database name is used."},
        "1230": {
            "error_num": 1230,
            "title": "ARANGO_USE_SYSTEM_DATABASE",
            "description": "Will be raised when an operation is requested in a database other than the system database.",
        },
        "1232": {
            "error_num": 1232,
            "title": "ARANGO_INVALID_KEY_GENERATOR",
            "description": "Will be raised when an invalid key generator description is used.",
        },
        "1233": {
            "error_num": 1233,
            "title": "ARANGO_INVALID_EDGE_ATTRIBUTE",
            "description": "will be raised when the _from or _to values of an edge are undefined or contain an invalid value.",
        },
        "1235": {"error_num": 1235, "title": "ARANGO_INDEX_CREATION_FAILED", "description": "Will be raised when an attempt to create an index has failed."},
        "1237": {
            "error_num": 1237,
            "title": "ARANGO_COLLECTION_TYPE_MISMATCH",
            "description": "Will be raised when a collection has a different type from what has been expected.",
        },
        "1238": {
            "error_num": 1238,
            "title": "ARANGO_COLLECTION_NOT_LOADED",
            "description": "Will be raised when a collection is accessed that is not yet loaded.",
        },
        "1239": {
            "error_num": 1239,
            "title": "ARANGO_DOCUMENT_REV_BAD",
            "description": "Will be raised when a document revision is corrupt or is missing where needed.",
        },
        "1240": {"error_num": 1240, "title": "ARANGO_INCOMPLETE_READ", "description": "Will be raised by the storage engine when a read cannot be completed."},
    },
    "Checked ArangoDB storage errors": {
        "1301": {"error_num": 1301, "title": "ARANGO_EMPTY_DATADIR", "description": "Will be raised when encountering an empty server database directory."},
        "1302": {"error_num": 1302, "title": "ARANGO_TRY_AGAIN", "description": "Will be raised when an operation should be retried."},
        "1303": {"error_num": 1303, "title": "ARANGO_BUSY", "description": "Will be raised when storage engine is busy."},
        "1304": {
            "error_num": 1304,
            "title": "ARANGO_MERGE_IN_PROGRESS",
            "description": "Will be raised when storage engine has a datafile merge in progress and cannot complete the operation.",
        },
        "1305": {"error_num": 1305, "title": "ARANGO_IO_ERROR", "description": "Will be raised when storage engine encounters an I/O error."},
    },
    "ArangoDB replication errors": {
        "1400": {
            "error_num": 1400,
            "title": "REPLICATION_NO_RESPONSE",
            "description": "Will be raised when the replication applier does not receive any or an incomplete response from the leader.",
        },
        "1401": {
            "error_num": 1401,
            "title": "REPLICATION_INVALID_RESPONSE",
            "description": "Will be raised when the replication applier receives an invalid response from the leader.",
        },
        "1402": {
            "error_num": 1402,
            "title": "REPLICATION_LEADER_ERROR",
            "description": "Will be raised when the replication applier receives a server error from the leader.",
        },
        "1403": {
            "error_num": 1403,
            "title": "REPLICATION_LEADER_INCOMPATIBLE",
            "description": "Will be raised when the replication applier connects to a leader that has an incompatible version.",
        },
        "1404": {
            "error_num": 1404,
            "title": "REPLICATION_LEADER_CHANGE",
            "description": "Will be raised when the replication applier connects to a different leader than before.",
        },
        "1405": {
            "error_num": 1405,
            "title": "REPLICATION_LOOP",
            "description": "Will be raised when the replication applier is asked to connect to itself for replication.",
        },
        "1406": {
            "error_num": 1406,
            "title": "REPLICATION_UNEXPECTED_MARKER",
            "description": "Will be raised when an unexpected marker is found in the replication log stream.",
        },
        "1407": {
            "error_num": 1407,
            "title": "REPLICATION_INVALID_APPLIER_STATE",
            "description": "Will be raised when an invalid replication applier state file is found.",
        },
        "1408": {"error_num": 1408, "title": "REPLICATION_UNEXPECTED_TRANSACTION", "description": "Will be raised when an unexpected transaction id is found."},
        "1409": {
            "error_num": 1409,
            "title": "REPLICATION_SHARD_SYNC_ATTEMPT_TIMEOUT_EXCEEDED",
            "description": "Will be raised when the synchronization of a shard takes longer than the configured timeout.",
        },
        "1410": {
            "error_num": 1410,
            "title": "REPLICATION_INVALID_APPLIER_CONFIGURATION",
            "description": "Will be raised when the configuration for the replication applier is invalid.",
        },
        "1411": {
            "error_num": 1411,
            "title": "REPLICATION_RUNNING",
            "description": "Will be raised when there is an attempt to perform an operation while the replication applier is running.",
        },
        "1412": {
            "error_num": 1412,
            "title": "REPLICATION_APPLIER_STOPPED",
            "description": "Special error code used to indicate the replication applier was stopped by a user.",
        },
        "1413": {
            "error_num": 1413,
            "title": "REPLICATION_NO_START_TICK",
            "description": "Will be raised when the replication applier is started without a known start tick value.",
        },
        "1414": {
            "error_num": 1414,
            "title": "REPLICATION_START_TICK_NOT_PRESENT",
            "description": "Will be raised when the replication applier fetches data using a start tick",
        },
        "1416": {"error_num": 1416, "title": "REPLICATION_WRONG_CHECKSUM", "description": "Will be raised when a new born follower submits a wrong checksum"},
        "1417": {
            "error_num": 1417,
            "title": "REPLICATION_SHARD_NONEMPTY",
            "description": "Will be raised when a shard is not empty and the follower tries a shortcut",
        },
        "1418": {
            "error_num": 1418,
            "title": "REPLICATION_REPLICATED_LOG_NOT_FOUND",
            "description": "Will be raised when a specific replicated log is not found",
        },
        "1419": {
            "error_num": 1419,
            "title": "REPLICATION_REPLICATED_LOG_NOT_THE_LEADER",
            "description": "Will be raised when a participant of a replicated log is ordered to do something only the leader can do",
        },
        "1420": {
            "error_num": 1420,
            "title": "REPLICATION_REPLICATED_LOG_NOT_A_FOLLOWER",
            "description": "Will be raised when a participant of a replicated log is ordered to do something only a follower can do",
        },
        "1421": {
            "error_num": 1421,
            "title": "REPLICATION_REPLICATED_LOG_APPEND_ENTRIES_REJECTED",
            "description": "Will be raised when a follower of a replicated log rejects an append entries request",
        },
        "1422": {
            "error_num": 1422,
            "title": "REPLICATION_REPLICATED_LOG_LEADER_RESIGNED",
            "description": "Will be raised when a leader instance of a replicated log rejects a request because it just resigned. This can also happen if the term changes (due to a configuration change)",
        },
        "1423": {
            "error_num": 1423,
            "title": "REPLICATION_REPLICATED_LOG_FOLLOWER_RESIGNED",
            "description": "Will be raised when a follower instance of a replicated log rejects a request because it just resigned. This can also happen if the term changes (due to a configuration change)",
        },
        "1424": {
            "error_num": 1424,
            "title": "REPLICATION_REPLICATED_LOG_PARTICIPANT_GONE",
            "description": "Will be raised when a participant instance of a replicated log is no longer available.",
        },
        "1425": {
            "error_num": 1425,
            "title": "REPLICATION_REPLICATED_LOG_INVALID_TERM",
            "description": "Will be raised when a participant tries to change its term but found a invalid new term.",
        },
        "1426": {
            "error_num": 1426,
            "title": "REPLICATION_REPLICATED_LOG_UNCONFIGURED",
            "description": "Will be raised when a participant is currently unconfigured",
        },
        "1427": {
            "error_num": 1427,
            "title": "REPLICATION_REPLICATED_STATE_NOT_FOUND",
            "description": "Will be raised when a specific replicated state was not found.",
        },
    },
    "ArangoDB cluster errors": {
        "1446": {"error_num": 1446, "title": "CLUSTER_NOT_FOLLOWER", "description": "Will be raised when an operation is sent to a non-following server."},
        "1447": {
            "error_num": 1447,
            "title": "CLUSTER_FOLLOWER_TRANSACTION_COMMIT_PERFORMED",
            "description": "Will be raised when a follower transaction has already performed an intermediate commit and must be rolled back.",
        },
        "1448": {
            "error_num": 1448,
            "title": "CLUSTER_CREATE_COLLECTION_PRECONDITION_FAILED",
            "description": "Will be raised when updating the plan on collection creation failed.",
        },
        "1449": {
            "error_num": 1449,
            "title": "CLUSTER_SERVER_UNKNOWN",
            "description": "Will be raised on some occasions when one server gets a request from another",
        },
        "1450": {
            "error_num": 1450,
            "title": "CLUSTER_TOO_MANY_SHARDS",
            "description": "Will be raised when the number of shards for a collection is higher than allowed.",
        },
        "1454": {
            "error_num": 1454,
            "title": "CLUSTER_COULD_NOT_CREATE_COLLECTION_IN_PLAN",
            "description": "Will be raised when a Coordinator in a cluster cannot create an entry for a new collection in the Plan hierarchy in the Agency.",
        },
        "1456": {
            "error_num": 1456,
            "title": "CLUSTER_COULD_NOT_CREATE_COLLECTION",
            "description": "Will be raised when a Coordinator in a cluster notices that some DB-Servers report problems when creating shards for a new collection.",
        },
        "1457": {
            "error_num": 1457,
            "title": "CLUSTER_TIMEOUT",
            "description": "Will be raised when a Coordinator in a cluster runs into a timeout for some cluster wide operation.",
        },
        "1458": {
            "error_num": 1458,
            "title": "CLUSTER_COULD_NOT_REMOVE_COLLECTION_IN_PLAN",
            "description": "Will be raised when a Coordinator in a cluster cannot remove an entry for a collection in the Plan hierarchy in the Agency.",
        },
        "1460": {
            "error_num": 1460,
            "title": "CLUSTER_COULD_NOT_CREATE_DATABASE_IN_PLAN",
            "description": "Will be raised when a Coordinator in a cluster cannot create an entry for a new database in the Plan hierarchy in the Agency.",
        },
        "1461": {
            "error_num": 1461,
            "title": "CLUSTER_COULD_NOT_CREATE_DATABASE",
            "description": "Will be raised when a Coordinator in a cluster notices that some DB-Servers report problems when creating databases for a new cluster wide database.",
        },
        "1462": {
            "error_num": 1462,
            "title": "CLUSTER_COULD_NOT_REMOVE_DATABASE_IN_PLAN",
            "description": "Will be raised when a Coordinator in a cluster cannot remove an entry for a database in the Plan hierarchy in the Agency.",
        },
        "1463": {
            "error_num": 1463,
            "title": "CLUSTER_COULD_NOT_REMOVE_DATABASE_IN_CURRENT",
            "description": "Will be raised when a Coordinator in a cluster cannot remove an entry for a database in the Current hierarchy in the Agency.",
        },
        "1464": {
            "error_num": 1464,
            "title": "CLUSTER_SHARD_GONE",
            "description": "Will be raised when a Coordinator in a cluster cannot determine the shard that is responsible for a given document.",
        },
        "1465": {
            "error_num": 1465,
            "title": "CLUSTER_CONNECTION_LOST",
            "description": "Will be raised when a Coordinator in a cluster loses an HTTP connection to a DB-Server in the cluster whilst transferring data.",
        },
        "1466": {
            "error_num": 1466,
            "title": "CLUSTER_MUST_NOT_SPECIFY_KEY",
            "description": "Will be raised when a Coordinator in a cluster finds that the _key attribute was specified in a sharded collection the uses not only _key as sharding attribute.",
        },
        "1467": {
            "error_num": 1467,
            "title": "CLUSTER_GOT_CONTRADICTING_ANSWERS",
            "description": "Will be raised if a Coordinator in a cluster gets conflicting results from different shards",
        },
        "1468": {
            "error_num": 1468,
            "title": "CLUSTER_NOT_ALL_SHARDING_ATTRIBUTES_GIVEN",
            "description": "Will be raised if a Coordinator tries to find out which shard is responsible for a partial document",
        },
        "1469": {
            "error_num": 1469,
            "title": "CLUSTER_MUST_NOT_CHANGE_SHARDING_ATTRIBUTES",
            "description": "Will be raised if there is an attempt to update the value of a shard attribute.",
        },
        "1470": {
            "error_num": 1470,
            "title": "CLUSTER_UNSUPPORTED",
            "description": "Will be raised when there is an attempt to carry out an operation that is not supported in the context of a sharded collection.",
        },
        "1471": {
            "error_num": 1471,
            "title": "CLUSTER_ONLY_ON_COORDINATOR",
            "description": "Will be raised if there is an attempt to run a Coordinator-only operation on a different type of node.",
        },
        "1472": {
            "error_num": 1472,
            "title": "CLUSTER_READING_PLAN_AGENCY",
            "description": "Will be raised if a Coordinator or DB-Server cannot read the Plan in the Agency.",
        },
        "1473": {
            "error_num": 1473,
            "title": "CLUSTER_COULD_NOT_TRUNCATE_COLLECTION",
            "description": "Will be raised if a Coordinator cannot truncate all shards of a cluster collection.",
        },
        "1474": {
            "error_num": 1474,
            "title": "CLUSTER_AQL_COMMUNICATION",
            "description": "Will be raised if the internal communication of the cluster for AQL produces an error.",
        },
        "1477": {
            "error_num": 1477,
            "title": "CLUSTER_ONLY_ON_DBSERVER",
            "description": "Will be raised if there is an attempt to run a DB-Server-only operation on a different type of node.",
        },
        "1478": {"error_num": 1478, "title": "CLUSTER_BACKEND_UNAVAILABLE", "description": "Will be raised if a required DB-Server can\u2019t be reached."},
        "1481": {
            "error_num": 1481,
            "title": "CLUSTER_AQL_COLLECTION_OUT_OF_SYNC",
            "description": "Will be raised if a collection/view needed during query execution is out of sync. This currently can happen when using SatelliteCollections",
        },
        "1482": {
            "error_num": 1482,
            "title": "CLUSTER_COULD_NOT_CREATE_INDEX_IN_PLAN",
            "description": "Will be raised when a Coordinator in a cluster cannot create an entry for a new index in the Plan hierarchy in the Agency.",
        },
        "1483": {
            "error_num": 1483,
            "title": "CLUSTER_COULD_NOT_DROP_INDEX_IN_PLAN",
            "description": "Will be raised when a Coordinator in a cluster cannot remove an index from the Plan hierarchy in the Agency.",
        },
        "1484": {
            "error_num": 1484,
            "title": "CLUSTER_CHAIN_OF_DISTRIBUTESHARDSLIKE",
            "description": "Will be raised if one tries to create a collection with a distributeShardsLike attribute which points to another collection that also has one.",
        },
        "1485": {
            "error_num": 1485,
            "title": "CLUSTER_MUST_NOT_DROP_COLL_OTHER_DISTRIBUTESHARDSLIKE",
            "description": "Will be raised if one tries to drop a collection to which another collection points with its distributeShardsLike attribute.",
        },
        "1486": {
            "error_num": 1486,
            "title": "CLUSTER_UNKNOWN_DISTRIBUTESHARDSLIKE",
            "description": "Will be raised if one tries to create a collection which points to an unknown collection in its distributeShardsLike attribute.",
        },
        "1487": {
            "error_num": 1487,
            "title": "CLUSTER_INSUFFICIENT_DBSERVERS",
            "description": "Will be raised if one tries to create a collection with a replicationFactor greater than the available number of DB-Servers.",
        },
        "1488": {
            "error_num": 1488,
            "title": "CLUSTER_COULD_NOT_DROP_FOLLOWER",
            "description": "Will be raised if a follower that ought to be dropped could not be dropped in the Agency (under Current).",
        },
        "1489": {
            "error_num": 1489,
            "title": "CLUSTER_SHARD_LEADER_REFUSES_REPLICATION",
            "description": "Will be raised if a replication operation is refused by a shard leader.",
        },
        "1490": {
            "error_num": 1490,
            "title": "CLUSTER_SHARD_FOLLOWER_REFUSES_OPERATION",
            "description": "Will be raised if a replication operation is refused by a shard follower because it is coming from the wrong leader.",
        },
        "1491": {"error_num": 1491, "title": "CLUSTER_SHARD_LEADER_RESIGNED", "description": "because it has resigned in the meantime"},
        "1492": {
            "error_num": 1492,
            "title": "CLUSTER_AGENCY_COMMUNICATION_FAILED",
            "description": "Will be raised if after various retries an Agency operation could not be performed successfully.",
        },
        "1495": {
            "error_num": 1495,
            "title": "CLUSTER_LEADERSHIP_CHALLENGE_ONGOING",
            "description": "Will be raised when servers are currently competing for leadership",
        },
        "1496": {"error_num": 1496, "title": "CLUSTER_NOT_LEADER", "description": "Will be raised when an operation is sent to a non-leading server."},
        "1497": {
            "error_num": 1497,
            "title": "CLUSTER_COULD_NOT_CREATE_VIEW_IN_PLAN",
            "description": "Will be raised when a Coordinator in a cluster cannot create an entry for a new View in the Plan hierarchy in the Agency.",
        },
        "1498": {
            "error_num": 1498,
            "title": "CLUSTER_VIEW_ID_EXISTS",
            "description": "Will be raised when a Coordinator in a cluster tries to create a View and the View ID already exists.",
        },
        "1499": {
            "error_num": 1499,
            "title": "CLUSTER_COULD_NOT_DROP_COLLECTION",
            "description": "Will be raised when a Coordinator in a cluster cannot drop a collection entry in the Plan hierarchy in the Agency.",
        },
    },
    "ArangoDB query errors": {
        "1500": {"error_num": 1500, "title": "QUERY_KILLED", "description": "Will be raised when a running query is killed by an explicit admin command."},
        "1501": {"error_num": 1501, "title": "QUERY_PARSE", "description": "Will be raised when query is parsed and is found to be syntactically invalid."},
        "1502": {"error_num": 1502, "title": "QUERY_EMPTY", "description": "Will be raised when an empty query is specified."},
        "1503": {"error_num": 1503, "title": "QUERY_SCRIPT", "description": "Will be raised when a runtime error is caused by the query."},
        "1504": {"error_num": 1504, "title": "QUERY_NUMBER_OUT_OF_RANGE", "description": "Will be raised when a number is outside the expected range."},
        "1505": {
            "error_num": 1505,
            "title": "QUERY_INVALID_GEO_VALUE",
            "description": "Will be raised when a geo index coordinate is invalid or out of range.",
        },
        "1510": {"error_num": 1510, "title": "QUERY_VARIABLE_NAME_INVALID", "description": "Will be raised when an invalid variable name is used."},
        "1511": {"error_num": 1511, "title": "QUERY_VARIABLE_REDECLARED", "description": "Will be raised when a variable gets re-assigned in a query."},
        "1512": {
            "error_num": 1512,
            "title": "QUERY_VARIABLE_NAME_UNKNOWN",
            "description": "Will be raised when an unknown variable is used or the variable is undefined the context it is used.",
        },
        "1521": {
            "error_num": 1521,
            "title": "QUERY_COLLECTION_LOCK_FAILED",
            "description": "Will be raised when a read lock on the collection cannot be acquired.",
        },
        "1522": {
            "error_num": 1522,
            "title": "QUERY_TOO_MANY_COLLECTIONS",
            "description": "Will be raised when the number of collections or shards in a query is beyond the allowed value.",
        },
        "1524": {
            "error_num": 1524,
            "title": "QUERY_TOO_MUCH_NESTING",
            "description": "Will be raised when a query contains expressions or other constructs with too many objects or that are too deeply nested.",
        },
        "1539": {
            "error_num": 1539,
            "title": "QUERY_INVALID_OPTIONS_ATTRIBUTE",
            "description": "Will be raised when an unknown attribute is used inside an OPTIONS clause.",
        },
        "1540": {"error_num": 1540, "title": "QUERY_FUNCTION_NAME_UNKNOWN", "description": "Will be raised when an undefined function is called."},
        "1541": {"error_num": 1541, "title": "QUERY_FUNCTION_ARGUMENT_NUMBER_MISMATCH", "description": "expected number of arguments: minimum: %d"},
        "1542": {
            "error_num": 1542,
            "title": "QUERY_FUNCTION_ARGUMENT_TYPE_MISMATCH",
            "description": "Will be raised when the type of an argument used in a function call does not match the expected argument type.",
        },
        "1543": {
            "error_num": 1543,
            "title": "QUERY_INVALID_REGEX",
            "description": "Will be raised when an invalid regex argument value is used in a call to a function that expects a regex.",
        },
        "1550": {
            "error_num": 1550,
            "title": "QUERY_BIND_PARAMETERS_INVALID",
            "description": "Will be raised when the structure of bind parameters passed has an unexpected format.",
        },
        "1551": {
            "error_num": 1551,
            "title": "QUERY_BIND_PARAMETER_MISSING",
            "description": "Will be raised when a bind parameter was declared in the query but the query is being executed with no value for that parameter.",
        },
        "1552": {
            "error_num": 1552,
            "title": "QUERY_BIND_PARAMETER_UNDECLARED",
            "description": "Will be raised when a value gets specified for an undeclared bind parameter.",
        },
        "1553": {"error_num": 1553, "title": "QUERY_BIND_PARAMETER_TYPE", "description": "Will be raised when a bind parameter has an invalid value or type."},
        "1561": {
            "error_num": 1561,
            "title": "QUERY_INVALID_ARITHMETIC_VALUE",
            "description": "Will be raised when a non-numeric value is used in an arithmetic operation.",
        },
        "1562": {"error_num": 1562, "title": "QUERY_DIVISION_BY_ZERO", "description": "Will be raised when there is an attempt to divide by zero."},
        "1563": {
            "error_num": 1563,
            "title": "QUERY_ARRAY_EXPECTED",
            "description": "Will be raised when a non-array operand is used for an operation that expects an array argument operand.",
        },
        "1568": {
            "error_num": 1568,
            "title": "QUERY_COLLECTION_USED_IN_EXPRESSION",
            "description": "Will be raised when a collection is used as an operand in an AQL expression.",
        },
        "1569": {"error_num": 1569, "title": "QUERY_FAIL_CALLED", "description": "Will be raised when the function FAIL() is called from inside a query."},
        "1570": {
            "error_num": 1570,
            "title": "QUERY_GEO_INDEX_MISSING",
            "description": "Will be raised when a geo restriction was specified but no suitable geo index is found to resolve it.",
        },
        "1571": {
            "error_num": 1571,
            "title": "QUERY_FULLTEXT_INDEX_MISSING",
            "description": "Will be raised when a fulltext query is performed on a collection without a suitable fulltext index.",
        },
        "1572": {"error_num": 1572, "title": "QUERY_INVALID_DATE_VALUE", "description": "Will be raised when a value cannot be converted to a date."},
        "1573": {
            "error_num": 1573,
            "title": "QUERY_MULTI_MODIFY",
            "description": "Will be raised when an AQL query contains more than one data-modifying operation.",
        },
        "1574": {
            "error_num": 1574,
            "title": "QUERY_INVALID_AGGREGATE_EXPRESSION",
            "description": "Will be raised when an AQL query contains an invalid aggregate expression.",
        },
        "1575": {
            "error_num": 1575,
            "title": "QUERY_COMPILE_TIME_OPTIONS",
            "description": "Will be raised when an AQL query contains OPTIONS that cannot be figured out at query compile time.",
        },
        "1577": {"error_num": 1577, "title": "QUERY_FORCED_INDEX_HINT_UNUSABLE", "description": "Will be raised when forceIndexHint is specified"},
        "1578": {
            "error_num": 1578,
            "title": "QUERY_DISALLOWED_DYNAMIC_CALL",
            "description": "Will be raised when a dynamic function call is made to a function that cannot be called dynamically.",
        },
        "1579": {
            "error_num": 1579,
            "title": "QUERY_ACCESS_AFTER_MODIFICATION",
            "description": "Will be raised when collection data are accessed after a data-modification operation.",
        },
    },
    "AQL user function errors": {
        "1580": {
            "error_num": 1580,
            "title": "QUERY_FUNCTION_INVALID_NAME",
            "description": "Will be raised when a user function with an invalid name is registered.",
        },
        "1581": {
            "error_num": 1581,
            "title": "QUERY_FUNCTION_INVALID_CODE",
            "description": "Will be raised when a user function is registered with invalid code.",
        },
        "1582": {"error_num": 1582, "title": "QUERY_FUNCTION_NOT_FOUND", "description": "Will be raised when a user function is accessed but not found."},
        "1583": {"error_num": 1583, "title": "QUERY_FUNCTION_RUNTIME_ERROR", "description": "Will be raised when a user function throws a runtime exception."},
    },
    "AQL query registry errors": {
        "1590": {"error_num": 1590, "title": "QUERY_BAD_JSON_PLAN", "description": "Will be raised when an HTTP API for a query got an invalid JSON object."},
        "1591": {"error_num": 1591, "title": "QUERY_NOT_FOUND", "description": "Will be raised when an Id of a query is not found by the HTTP API."},
        "1593": {"error_num": 1593, "title": "QUERY_USER_ASSERT", "description": "Will be raised if and user provided expression fails to evaluate to true"},
        "1594": {"error_num": 1594, "title": "QUERY_USER_WARN", "description": "Will be raised if and user provided expression fails to evaluate to true"},
        "1595": {
            "error_num": 1595,
            "title": "QUERY_WINDOW_AFTER_MODIFICATION",
            "description": "Will be raised when a window node is created after a data-modification operation.",
        },
    },
    "ArangoDB cursor errors": {
        "1600": {
            "error_num": 1600,
            "title": "CURSOR_NOT_FOUND",
            "description": "Will be raised when a cursor is requested via its id but a cursor with that id cannot be found.",
        },
        "1601": {
            "error_num": 1601,
            "title": "CURSOR_BUSY",
            "description": "Will be raised when a cursor is requested via its id but a concurrent request is still using the cursor.",
        },
    },
    "ArangoDB schema validation errors": {
        "1620": {"error_num": 1620, "title": "VALIDATION_FAILED", "description": "Will be raised when a document does not pass schema validation."},
        "1621": {"error_num": 1621, "title": "VALIDATION_BAD_PARAMETER", "description": "Will be raised when the schema description is invalid."},
    },
    "ArangoDB transaction errors": {
        "1650": {
            "error_num": 1650,
            "title": "TRANSACTION_INTERNAL",
            "description": "Will be raised when a wrong usage of transactions is detected. this is an internal error and indicates a bug in ArangoDB.",
        },
        "1651": {"error_num": 1651, "title": "TRANSACTION_NESTED", "description": "Will be raised when transactions are nested."},
        "1652": {
            "error_num": 1652,
            "title": "TRANSACTION_UNREGISTERED_COLLECTION",
            "description": "Will be raised when a collection is used in the middle of a transaction but was not registered at transaction start.",
        },
        "1653": {
            "error_num": 1653,
            "title": "TRANSACTION_DISALLOWED_OPERATION",
            "description": "Will be raised when a disallowed operation is carried out in a transaction.",
        },
        "1654": {"error_num": 1654, "title": "TRANSACTION_ABORTED", "description": "Will be raised when a transaction was aborted."},
        "1655": {"error_num": 1655, "title": "TRANSACTION_NOT_FOUND", "description": "Will be raised when a transaction was not found."},
    },
    "User management errors": {
        "1700": {"error_num": 1700, "title": "USER_INVALID_NAME", "description": "Will be raised when an invalid user name is used."},
        "1702": {"error_num": 1702, "title": "USER_DUPLICATE", "description": "Will be raised when a user name already exists."},
        "1703": {"error_num": 1703, "title": "USER_NOT_FOUND", "description": "Will be raised when a user name is updated that does not exist."},
        "1705": {"error_num": 1705, "title": "USER_EXTERNAL", "description": "Will be raised when the user is authenticated by an external server."},
    },
    "Service management errors (legacy)": {
        "1752": {
            "error_num": 1752,
            "title": "SERVICE_DOWNLOAD_FAILED",
            "description": "Will be raised when a service download from the central repository failed.",
        },
        "1753": {
            "error_num": 1753,
            "title": "SERVICE_UPLOAD_FAILED",
            "description": "Will be raised when a service upload from the client to the ArangoDB server failed.",
        },
    },
    "LDAP errors": {
        "1800": {"error_num": 1800, "title": "LDAP_CANNOT_INIT", "description": "can not init a LDAP connection"},
        "1801": {"error_num": 1801, "title": "LDAP_CANNOT_SET_OPTION", "description": "can not set a LDAP option"},
        "1802": {"error_num": 1802, "title": "LDAP_CANNOT_BIND", "description": "can not bind to a LDAP server"},
        "1803": {"error_num": 1803, "title": "LDAP_CANNOT_UNBIND", "description": "can not unbind from a LDAP server"},
        "1804": {"error_num": 1804, "title": "LDAP_CANNOT_SEARCH", "description": "can not search the LDAP server"},
        "1805": {"error_num": 1805, "title": "LDAP_CANNOT_START_TLS", "description": "can not star a TLS LDAP session"},
        "1806": {"error_num": 1806, "title": "LDAP_FOUND_NO_OBJECTS", "description": "LDAP didn\u2019t found any objects with the specified search query"},
        "1807": {"error_num": 1807, "title": "LDAP_NOT_ONE_USER_FOUND", "description": "LDAP found zero ore more than one user"},
        "1808": {"error_num": 1808, "title": "LDAP_USER_NOT_IDENTIFIED", "description": "but its not the desired one"},
        "1809": {"error_num": 1809, "title": "LDAP_OPERATIONS_ERROR", "description": "LDAP returned an operations error"},
        "1820": {"error_num": 1820, "title": "LDAP_INVALID_MODE", "description": "cant distinguish a valid mode for provided LDAP configuration"},
    },
    "Task errors": {
        "1850": {"error_num": 1850, "title": "TASK_INVALID_ID", "description": "Will be raised when a task is created with an invalid id."},
        "1851": {"error_num": 1851, "title": "TASK_DUPLICATE_ID", "description": "Will be raised when a task id is created with a duplicate id."},
        "1852": {"error_num": 1852, "title": "TASK_NOT_FOUND", "description": "Will be raised when a task with the specified id could not be found."},
    },
    "Graph / traversal errors": {
        "1901": {"error_num": 1901, "title": "GRAPH_INVALID_GRAPH", "description": "Will be raised when an invalid name is passed to the server."},
        "1906": {"error_num": 1906, "title": "GRAPH_INVALID_EDGE", "description": "Will be raised when an invalid edge id is passed to the server."},
        "1909": {
            "error_num": 1909,
            "title": "GRAPH_TOO_MANY_ITERATIONS",
            "description": "Will be raised when too many iterations are done in a graph traversal.",
        },
        "1910": {
            "error_num": 1910,
            "title": "GRAPH_INVALID_FILTER_RESULT",
            "description": "Will be raised when an invalid filter result is returned in a graph traversal.",
        },
        "1920": {
            "error_num": 1920,
            "title": "GRAPH_COLLECTION_MULTI_USE",
            "description": "an edge collection may only be used once in one edge definition of a graph.",
        },
        "1921": {
            "error_num": 1921,
            "title": "GRAPH_COLLECTION_USE_IN_MULTI_GRAPHS",
            "description": "is already used by another graph in a different edge definition.",
        },
        "1922": {"error_num": 1922, "title": "GRAPH_CREATE_MISSING_NAME", "description": "a graph name is required to create or drop a graph."},
        "1923": {
            "error_num": 1923,
            "title": "GRAPH_CREATE_MALFORMED_EDGE_DEFINITION",
            "description": "the edge definition is malformed. It has to be an array of objects.",
        },
        "1924": {"error_num": 1924, "title": "GRAPH_NOT_FOUND", "description": "a graph with this name could not be found."},
        "1925": {"error_num": 1925, "title": "GRAPH_DUPLICATE", "description": "a graph with this name already exists."},
        "1926": {
            "error_num": 1926,
            "title": "GRAPH_VERTEX_COL_DOES_NOT_EXIST",
            "description": "the specified vertex collection does not exist or is not part of the graph.",
        },
        "1927": {"error_num": 1927, "title": "GRAPH_WRONG_COLLECTION_TYPE_VERTEX", "description": "the collection is not a vertex collection."},
        "1928": {
            "error_num": 1928,
            "title": "GRAPH_NOT_IN_ORPHAN_COLLECTION",
            "description": "Vertex collection not in list of orphan collections of the graph.",
        },
        "1929": {
            "error_num": 1929,
            "title": "GRAPH_COLLECTION_USED_IN_EDGE_DEF",
            "description": "The collection is already used in an edge definition of the graph.",
        },
        "1930": {
            "error_num": 1930,
            "title": "GRAPH_EDGE_COLLECTION_NOT_USED",
            "description": "The edge collection is not used in any edge definition of the graph.",
        },
        "1932": {"error_num": 1932, "title": "GRAPH_NO_GRAPH_COLLECTION", "description": "collection _graphs does not exist."},
        "1935": {"error_num": 1935, "title": "GRAPH_INVALID_NUMBER_OF_ARGUMENTS", "description": "Invalid number of arguments. Expected:"},
        "1936": {"error_num": 1936, "title": "GRAPH_INVALID_PARAMETER", "description": "Invalid parameter type."},
        "1938": {"error_num": 1938, "title": "GRAPH_COLLECTION_USED_IN_ORPHANS", "description": "The collection is already used in the orphans of the graph."},
        "1939": {
            "error_num": 1939,
            "title": "GRAPH_EDGE_COL_DOES_NOT_EXIST",
            "description": "the specified edge collection does not exist or is not part of the graph.",
        },
        "1940": {"error_num": 1940, "title": "GRAPH_EMPTY", "description": "The requested graph has no edge collections."},
        "1941": {"error_num": 1941, "title": "GRAPH_INTERNAL_DATA_CORRUPT", "description": "The _graphs collection contains invalid data."},
        "1943": {
            "error_num": 1943,
            "title": "GRAPH_CREATE_MALFORMED_ORPHAN_LIST",
            "description": "the orphan list argument is malformed. It has to be an array of strings.",
        },
        "1944": {"error_num": 1944, "title": "GRAPH_EDGE_DEFINITION_IS_DOCUMENT", "description": "the collection used as a relation is existing"},
        "1945": {
            "error_num": 1945,
            "title": "GRAPH_COLLECTION_IS_INITIAL",
            "description": "the collection is used as the initial collection of this graph and is not allowed to be removed manually.",
        },
        "1946": {
            "error_num": 1946,
            "title": "GRAPH_NO_INITIAL_COLLECTION",
            "description": "during the graph creation process no collection could be selected as the needed initial collection. Happens if a distributeShardsLike or replicationFactor mismatch was found.",
        },
        "1947": {
            "error_num": 1947,
            "title": "GRAPH_REFERENCED_VERTEX_COLLECTION_NOT_USED",
            "description": "the _from or _to collection specified for the edge refers to a vertex collection which is not used in any edge definition of the graph.",
        },
        "1948": {
            "error_num": 1948,
            "title": "GRAPH_NEGATIVE_EDGE_WEIGHT",
            "description": "a negative edge weight was found during a weighted graph traversal or shortest path query",
        },
    },
    "Session errors": {
        "1950": {"error_num": 1950, "title": "SESSION_UNKNOWN", "description": "Will be raised when an invalid/unknown session id is passed to the server."},
        "1951": {"error_num": 1951, "title": "SESSION_EXPIRED", "description": "Will be raised when a session is expired."},
    },
    "Simple Client errors": {
        "2000": {"error_num": 2000, "title": "SIMPLE_CLIENT_UNKNOWN_ERROR", "description": "This error should not happen."},
        "2001": {
            "error_num": 2001,
            "title": "SIMPLE_CLIENT_COULD_NOT_CONNECT",
            "description": "Will be raised when the client could not connect to the server.",
        },
        "2002": {"error_num": 2002, "title": "SIMPLE_CLIENT_COULD_NOT_WRITE", "description": "Will be raised when the client could not write data."},
        "2003": {"error_num": 2003, "title": "SIMPLE_CLIENT_COULD_NOT_READ", "description": "Will be raised when the client could not read data."},
        "2019": {"error_num": 2019, "title": "WAS_ERLAUBE", "description": "Will be raised if was erlaube?!"},
    },
    "internal AQL errors": {
        "2200": {"error_num": 2200, "title": "INTERNAL_AQL", "description": "Internal error during AQL execution"},
        "2201": {"error_num": 2201, "title": "WROTE_TOO_FEW_OUTPUT_REGISTERS", "description": "An AQL block wrote too few output registers"},
        "2202": {"error_num": 2202, "title": "WROTE_TOO_MANY_OUTPUT_REGISTERS", "description": "An AQL block wrote too many output registers"},
        "2203": {"error_num": 2203, "title": "WROTE_OUTPUT_REGISTER_TWICE", "description": "An AQL block wrote an output register twice"},
        "2204": {"error_num": 2204, "title": "WROTE_IN_WRONG_REGISTER", "description": "An AQL block wrote in a register that is not its output"},
        "2205": {"error_num": 2205, "title": "INPUT_REGISTERS_NOT_COPIED", "description": "An AQL block did not copy its input registers"},
    },
    "Foxx management errors": {
        "3000": {"error_num": 3000, "title": "MALFORMED_MANIFEST_FILE", "description": "The service manifest file is not well-formed JSON."},
        "3001": {"error_num": 3001, "title": "INVALID_SERVICE_MANIFEST", "description": "The service manifest contains invalid values."},
        "3002": {"error_num": 3002, "title": "SERVICE_FILES_MISSING", "description": "The service folder or bundle does not exist on this server."},
        "3003": {"error_num": 3003, "title": "SERVICE_FILES_OUTDATED", "description": "The local service bundle does not match the checksum in the database."},
        "3004": {"error_num": 3004, "title": "INVALID_FOXX_OPTIONS", "description": "The service options contain invalid values."},
        "3007": {"error_num": 3007, "title": "INVALID_MOUNTPOINT", "description": "The service mountpath contains invalid characters."},
        "3009": {"error_num": 3009, "title": "SERVICE_NOT_FOUND", "description": "No service found at the given mountpath."},
        "3010": {"error_num": 3010, "title": "SERVICE_NEEDS_CONFIGURATION", "description": "The service is missing configuration or dependencies."},
        "3011": {"error_num": 3011, "title": "SERVICE_MOUNTPOINT_CONFLICT", "description": "A service already exists at the given mountpath."},
        "3012": {"error_num": 3012, "title": "SERVICE_MANIFEST_NOT_FOUND", "description": "The service directory does not contain a manifest file."},
        "3013": {"error_num": 3013, "title": "SERVICE_OPTIONS_MALFORMED", "description": "The service options are not well-formed JSON."},
        "3014": {"error_num": 3014, "title": "SERVICE_SOURCE_NOT_FOUND", "description": "The source path does not match a file or directory."},
        "3015": {"error_num": 3015, "title": "SERVICE_SOURCE_ERROR", "description": "The source path could not be resolved."},
        "3016": {"error_num": 3016, "title": "SERVICE_UNKNOWN_SCRIPT", "description": "The service does not have a script with this name."},
        "3099": {"error_num": 3099, "title": "SERVICE_API_DISABLED", "description": "The API for managing Foxx services has been disabled on this server."},
    },
    "JavaScript module loader errors": {
        "3100": {"error_num": 3100, "title": "MODULE_NOT_FOUND", "description": "The module path could not be resolved."},
        "3101": {"error_num": 3101, "title": "MODULE_SYNTAX_ERROR", "description": "The module could not be parsed because of a syntax error."},
        "3103": {"error_num": 3103, "title": "MODULE_FAILURE", "description": "Failed to invoke the module in its context."},
    },
    "Enterprise Edition errors": {
        "4000": {"error_num": 4000, "title": "NO_SMART_COLLECTION", "description": "The requested collection needs to be smart"},
        "4001": {"error_num": 4001, "title": "NO_SMART_GRAPH_ATTRIBUTE", "description": "The given document does not have the SmartGraph attribute set."},
        "4002": {"error_num": 4002, "title": "CANNOT_DROP_SMART_COLLECTION", "description": "This smart collection cannot be dropped"},
        "4003": {
            "error_num": 4003,
            "title": "KEY_MUST_BE_PREFIXED_WITH_SMART_GRAPH_ATTRIBUTE",
            "description": "In a smart vertex collection _key must be prefixed with the value of the SmartGraph attribute.",
        },
        "4004": {
            "error_num": 4004,
            "title": "ILLEGAL_SMART_GRAPH_ATTRIBUTE",
            "description": "The given smartGraph attribute is illegal and cannot be used for sharding. All system attributes are forbidden.",
        },
        "4005": {
            "error_num": 4005,
            "title": "SMART_GRAPH_ATTRIBUTE_MISMATCH",
            "description": "The SmartGraph attribute of the given collection does not match the SmartGraph attribute of the graph.",
        },
        "4006": {
            "error_num": 4006,
            "title": "INVALID_SMART_JOIN_ATTRIBUTE",
            "description": "Will be raised when the smartJoinAttribute declaration is invalid.",
        },
        "4007": {"error_num": 4007, "title": "KEY_MUST_BE_PREFIXED_WITH_SMART_JOIN_ATTRIBUTE", "description": "when using smartJoinAttribute for a collection"},
        "4008": {
            "error_num": 4008,
            "title": "NO_SMART_JOIN_ATTRIBUTE",
            "description": "The given document does not have the required SmartJoin attribute set or it has an invalid value.",
        },
        "4009": {
            "error_num": 4009,
            "title": "CLUSTER_MUST_NOT_CHANGE_SMART_JOIN_ATTRIBUTE",
            "description": "Will be raised if there is an attempt to update the value of the smartJoinAttribute.",
        },
        "4010": {
            "error_num": 4010,
            "title": "INVALID_DISJOINT_SMART_EDGE",
            "description": "Will be raised if there is an attempt to create an edge between separated graph components.",
        },
        "4011": {
            "error_num": 4011,
            "title": "UNSUPPORTED_CHANGE_IN_SMART_TO_SATELLITE_DISJOINT_EDGE_DIRECTION",
            "description": "Switching back and forth between Satellite and Smart in Disjoint SmartGraph is not supported within a single AQL statement. Split into multiple statements.",
        },
    },
    "Agency errors": {
        "20001": {"error_num": 20001, "title": "AGENCY_MALFORMED_GOSSIP_MESSAGE", "description": "Malformed gossip message."},
        "20002": {"error_num": 20002, "title": "AGENCY_MALFORMED_INQUIRE_REQUEST", "description": "Malformed inquire request."},
        "20011": {"error_num": 20011, "title": "AGENCY_INFORM_MUST_BE_OBJECT", "description": "The inform message in the Agency must be an object."},
        "20012": {
            "error_num": 20012,
            "title": "AGENCY_INFORM_MUST_CONTAIN_TERM",
            "description": "The inform message in the Agency must contain a uint parameter \u2018term\u2019.",
        },
        "20013": {
            "error_num": 20013,
            "title": "AGENCY_INFORM_MUST_CONTAIN_ID",
            "description": "The inform message in the Agency must contain a string parameter \u2018id\u2019.",
        },
        "20014": {
            "error_num": 20014,
            "title": "AGENCY_INFORM_MUST_CONTAIN_ACTIVE",
            "description": "The inform message in the Agency must contain an array \u2018active\u2019.",
        },
        "20015": {
            "error_num": 20015,
            "title": "AGENCY_INFORM_MUST_CONTAIN_POOL",
            "description": "The inform message in the Agency must contain an object \u2018pool\u2019.",
        },
        "20016": {
            "error_num": 20016,
            "title": "AGENCY_INFORM_MUST_CONTAIN_MIN_PING",
            "description": "The inform message in the Agency must contain an object \u2018min ping\u2019.",
        },
        "20017": {
            "error_num": 20017,
            "title": "AGENCY_INFORM_MUST_CONTAIN_MAX_PING",
            "description": "The inform message in the Agency must contain an object \u2018max ping\u2019.",
        },
        "20018": {
            "error_num": 20018,
            "title": "AGENCY_INFORM_MUST_CONTAIN_TIMEOUT_MULT",
            "description": "The inform message in the Agency must contain an object \u2018timeoutMult\u2019.",
        },
        "20021": {
            "error_num": 20021,
            "title": "AGENCY_CANNOT_REBUILD_DBS",
            "description": "Will be raised if the readDB or the spearHead cannot be rebuilt from the replicated log.",
        },
        "20030": {"error_num": 20030, "title": "AGENCY_MALFORMED_TRANSACTION", "description": "Malformed agency transaction."},
    },
    "Supervision errors": {"20501": {"error_num": 20501, "title": "SUPERVISION_GENERAL_FAILURE", "description": "General supervision failure."}},
    "Scheduler errors": {
        "21003": {"error_num": 21003, "title": "QUEUE_FULL", "description": "Will be returned if the scheduler queue is full."},
        "21004": {
            "error_num": 21004,
            "title": "QUEUE_TIME_REQUIREMENT_VIOLATED",
            "description": "Will be returned if a request with a queue time requirement is set and it cannot be fulfilled.",
        },
    },
    "Maintenance errors": {
        "6002": {"error_num": 6002, "title": "ACTION_OPERATION_UNABORTABLE", "description": "This maintenance action cannot be stopped once it is started"},
        "6003": {"error_num": 6003, "title": "ACTION_UNFINISHED", "description": "This maintenance action is still processing"},
    },
    "Backup/Restore errors": {
        "7001": {"error_num": 7001, "title": "HOT_BACKUP_INTERNAL", "description": "Failed to create hot backup set"},
        "7002": {"error_num": 7002, "title": "HOT_RESTORE_INTERNAL", "description": "Failed to restore to hot backup set"},
        "7003": {"error_num": 7003, "title": "BACKUP_TOPOLOGY", "description": "The hot backup set cannot be restored on non matching cluster topology"},
        "7004": {"error_num": 7004, "title": "NO_SPACE_LEFT_ON_DEVICE", "description": "No space left on device"},
        "7005": {"error_num": 7005, "title": "FAILED_TO_UPLOAD_BACKUP", "description": "Failed to upload hot backup set to remote target"},
        "7006": {"error_num": 7006, "title": "FAILED_TO_DOWNLOAD_BACKUP", "description": "Failed to download hot backup set from remote source"},
        "7007": {"error_num": 7007, "title": "NO_SUCH_HOT_BACKUP", "description": "Cannot find a hot backup set with this Id"},
        "7008": {
            "error_num": 7008,
            "title": "REMOTE_REPOSITORY_CONFIG_BAD",
            "description": "The configuration given for upload or download operation to/from remote hot backup repositories is wrong.",
        },
        "7009": {"error_num": 7009, "title": "LOCAL_LOCK_FAILED", "description": "Some of the DB-Servers cannot be reached for transaction locks."},
        "7010": {"error_num": 7010, "title": "LOCAL_LOCK_RETRY", "description": "Some of the DB-Servers cannot be reached for transaction locks."},
        "7011": {"error_num": 7011, "title": "HOT_BACKUP_CONFLICT", "description": "Conflict of multiple hot backup processes."},
        "7012": {"error_num": 7012, "title": "HOT_BACKUP_DBSERVERS_AWOL", "description": "One or more DB-Servers could not be reached for hot backup inquiry"},
    },
    "Plan Analyzers errors": {
        "7021": {
            "error_num": 7021,
            "title": "CLUSTER_COULD_NOT_MODIFY_ANALYZERS_IN_PLAN",
            "description": "Plan could not be modified while creating or deleting Analyzers revision",
        }
    },
    "AIR errors": {"8001": {"error_num": 8001, "title": "AIR_EXECUTION_ERROR", "description": "During the execution of an AIR program an error occurred"}},
    "Licensing": {
        "9001": {"error_num": 9001, "title": "LICENSE_EXPIRED_OR_INVALID", "description": "The license has expired or is invalid."},
        "9002": {"error_num": 9002, "title": "LICENSE_SIGNATURE_VERIFICATION", "description": "Verification of license failed."},
        "9003": {"error_num": 9003, "title": "LICENSE_NON_MATCHING_ID", "description": "The ID of the license does not match the ID of this instance."},
        "9004": {"error_num": 9004, "title": "LICENSE_FEATURE_NOT_ENABLED", "description": "The installed license does not cover this feature."},
        "9005": {
            "error_num": 9005,
            "title": "LICENSE_RESOURCE_EXHAUSTED",
            "description": "The installed license does not cover a higher number of this resource.",
        },
        "9006": {"error_num": 9006, "title": "LICENSE_INVALID", "description": "The license does not hold features of an ArangoDB license."},
        "9007": {"error_num": 9007, "title": "LICENSE_CONFLICT", "description": "The license has one or more inferior features."},
        "9008": {"error_num": 9008, "title": "LICENSE_VALIDATION_FAILED", "description": "Could not verify the license\u2019s signature."},
    },
}
