from enum import Enum


class RabbitMQTaskType(Enum):
    UNKNOWN = -1
    DUMMY_TASK = -2

    ADD_CHANNEL_TASK = 0
    CHECK_USERNAME_TASK = 1
    EXTRACT_USERNAMES_TASK = 2
    INDEX_AUDIOS_TASK = 3
    REINDEX_AUDIOS_TASK = 4
    SHUTDOWN_TASK = 5
    FORWARD_MESSAGE_TASK = 6
    UPLOAD_AUDIO_THUMBNAIL_TASK = 7

    CHECK_USERNAMES_JOB = 100
    CHECK_USERNAMES_WITH_UNCHECKED_MENTIONS_JOB = 101
    DUMMY_JOB = 102
    FORWARD_AUDIOS_JOB = 103
    EXTRACT_USERNAMES_JOB = 104
    INDEX_AUDIOS_JOB = 105
    COUNT_AUDIO_INTERACTIONS_JOB = 106
    COUNT_PUBLIC_PLAYLIST_INTERACTIONS_JOB = 107
    COUNT_PUBLIC_PLAYLIST_SUBSCRIPTIONS_JOB = 108
    COUNT_HITS_JOB = 109
    UPLOAD_AUDIO_THUMBNAILS_JOB = 110
