from enum import Enum


class RabbitMQTaskType(Enum):
    UNKNOWN = -1
    DUMMY_TASK = -2

    ADD_CHANNEL_TASK = 0
    CHECK_USERNAME_TASK = 1
    EXTRACT_USERNAMES_TASK = 2
    INDEX_AUDIOS_TASK = 3
    SHUTDOWN_TASK = 4
    FORWARD_MESSAGE_TASK = 5

    CHECK_USERNAMES_JOB = 6
    CHECK_USERNAMES_WITH_UNCHECKED_MENTIONS_JOB = 7
    DUMMY_JOB = 8
    FORWARD_AUDIOS_JOB = 9
    EXTRACT_USERNAMES_JOB = 10
    INDEX_AUDIOS_JOB = 11
    COUNT_AUDIO_INTERACTIONS_JOB = 12
    COUNT_PUBLIC_PLAYLIST_INTERACTIONS_JOB = 13
    COUNT_PUBLIC_PLAYLIST_SUBSCRIPTIONS_JOB = 14
    COUNT_HITS_JOB = 15
