from enum import Enum


class InlineButtonType(Enum):
    UNKNOWN = 0
    INVALID = 1
    BASE = 2

    NOT_A_BUTTON = -1

    # commands intended for testing purposes
    # DUMMY = "dummy"

    ADD_TO_PLAYLIST = 3
    ADD_TO_FAVORITE_PLAYLIST = 4
    LIKE_AUDIO = 5
    DISLIKE_AUDIO = 6
    ADVERTISEMENT = 7
    BACK = 8
    BACK_TO_PLAYLISTS = 9
    SHOW_MORE_RESULTS = 10
    CHOOSE_LANGUAGE = 11
    DELETE_PLAYLIST = 12
    DOWNLOAD_HISTORY = 13
    EDIT_PLAYLIST_DESCRIPTION = 14
    EDIT_PLAYLIST_TITLE = 15
    GET_PLAYLIST_AUDIOS = 16
    HELP_CATALOG = 17
    HOME = 18
    TOGGLE_PLAYLIST_SETTINGS = 19
    TOGGLE_PLAYLIST_SUBSCRIPTION = 20
    DOWNLOAD_AUDIO = 21
    AUDIO_LOADING_KEYBOARD = 22
    MY_PLAYLISTS = 23
    MY_PLAYLIST_SUBSCRIPTIONS = 24
    SEARCH_AMONG_PUBLIC_PLAYLISTS = 25
    SHARE_PLAYLIST = 26
    REMOVE_FROM_PLAYLIST = 27
    SHOW_LANGUAGE_MENU = 28
    PLAYLIST_LOADING_KEYBOARD = 29
